# Generated by Django 2.2.7 on 2019-12-05 00:57

from django.db import migrations, models
import django.db.models.deletion
import shoutouts.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('talents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoutoutVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hash_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('file', models.FileField(max_length=140, upload_to=shoutouts.models.upload_location)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shoutout', to='orders.Order')),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talents.Talent')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
