# Generated by Django 2.2.7 on 2019-12-05 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WirecardTransactionData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wirecard_order_hash', models.CharField(max_length=50)),
                ('wirecard_payment_hash', models.CharField(max_length=50)),
                ('payment_event_last_timestamp', models.DateTimeField(null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='third_party_transaction', to='orders.Order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
