# Generated by Django 2.2.7 on 2019-12-06 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talents', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BankAccount',
            new_name='TalentBankAccount',
        ),
        migrations.RenameModel(
            old_name='DebtsPaymentLog',
            new_name='TalentProfitsPaymentLog',
        ),
        migrations.RenameField(
            model_name='talentprofitspaymentlog',
            old_name='paid_debts_ids_array',
            new_name='paid_profits_ids_array',
        ),
    ]
