# Generated by Django 2.2.7 on 2019-12-08 22:41

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talents', '0002_auto_20191206_0054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AgencyBankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fullname', models.CharField(max_length=100)),
                ('tax_document', models.CharField(max_length=14)),
                ('bank', models.CharField(max_length=80)),
                ('bank_transit_number', models.CharField(max_length=10)),
                ('bank_branch_number', models.CharField(max_length=10)),
                ('account_number', models.CharField(max_length=10)),
                ('account_control_digit', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='AgencyProfitsPaymentLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('num_viggios', models.PositiveSmallIntegerField()),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=7)),
                ('reference_month', models.DateField()),
                ('paid_profits_ids_array', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveConstraint(
            model_name='talentbankaccount',
            name='unique_bank_account',
        ),
        migrations.AddConstraint(
            model_name='talentbankaccount',
            constraint=models.UniqueConstraint(fields=('account_number', 'bank_transit_number'), name='unique_talent_bank_account'),
        ),
        migrations.AddField(
            model_name='agencyprofitspaymentlog',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talents.Agency'),
        ),
        migrations.AddField(
            model_name='agencybankaccount',
            name='agency',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_account', to='talents.Agency'),
        ),
        migrations.AddField(
            model_name='talent',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='talents', to='talents.Agency'),
        ),
        migrations.AddConstraint(
            model_name='agencybankaccount',
            constraint=models.UniqueConstraint(fields=('account_number', 'bank_transit_number'), name='unique_agency_bank_account'),
        ),
    ]
