# Generated by Django 2.2.7 on 2019-12-05 00:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('talents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=7)),
                ('payment_date', models.DateTimeField()),
                ('payment_method', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('not_processed', 'not processed'), ('processing', 'processing'), ('pre_authorized', 'pre-authorized'), ('paid', 'paid'), ('failed', 'failed'), ('cancelled', 'cancelled')], max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DefaultViggioCommissionPercentage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hash_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('video_is_for', models.CharField(choices=[('someone_else', 'someone else'), ('myself', 'myself')], max_length=100)),
                ('is_from', models.CharField(blank=True, max_length=80)),
                ('is_to', models.CharField(max_length=80)),
                ('instruction', models.TextField(blank=True)),
                ('email', models.EmailField(max_length=254)),
                ('expiration_datetime', models.DateTimeField()),
                ('is_public', models.BooleanField()),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talents.Talent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shoutout_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('commission_percentage', models.DecimalField(decimal_places=2, max_digits=3)),
                ('commission', models.DecimalField(decimal_places=2, max_digits=7)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('paid', models.BooleanField()),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='debt', to='orders.Order')),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='talents.Talent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomViggioCommissionPercentage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=3)),
                ('talent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='talents.Talent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fullname', models.CharField(max_length=100)),
                ('birthdate', models.DateField()),
                ('tax_document', models.CharField(max_length=11)),
                ('phone_number', models.CharField(max_length=9)),
                ('area_code', models.CharField(max_length=2)),
                ('credit_card_hash', models.CharField(max_length=550)),
                ('charge', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='funding_instrument', to='orders.Charge')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='charge',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='charge', to='orders.Order'),
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fullname', models.CharField(max_length=100)),
                ('birthdate', models.DateField()),
                ('tax_document', models.CharField(max_length=11)),
                ('phone_number', models.CharField(max_length=9)),
                ('area_code', models.CharField(max_length=2)),
                ('charge', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to='orders.Charge')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
