# Generated by Django 2.2.7 on 2019-12-06 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talents', '0002_auto_20191206_0054'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalentProfit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shoutout_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('profit_percentage', models.DecimalField(decimal_places=2, max_digits=3)),
                ('profit', models.DecimalField(decimal_places=2, max_digits=7)),
                ('paid', models.BooleanField()),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='talent_profit', to='orders.Order')),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profits', to='talents.Talent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='CustomViggioCommissionPercentage',
            new_name='CustomTalentProfitPercentage',
        ),
        migrations.RenameModel(
            old_name='DefaultViggioCommissionPercentage',
            new_name='DefaultTalentProfitPercentage',
        ),
        migrations.DeleteModel(
            name='Debt',
        ),
    ]
