# Generated by Django 2.2.7 on 2019-12-08 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talents', '0003_auto_20191208_2241'),
        ('orders', '0002_auto_20191206_0054'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyProfitPercentage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=3)),
                ('agency', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='talents.Agency')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AgencyProfit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shoutout_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('profit_percentage', models.DecimalField(decimal_places=2, max_digits=3)),
                ('profit', models.DecimalField(decimal_places=2, max_digits=7)),
                ('paid', models.BooleanField()),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profits', to='talents.Agency')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agency_profit', to='orders.Order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
